### ISSUE TITLE
Add a toggleable "..." to hide/show surfaces when there are too many

### ISSUE THREAD

**Issue by mechanikate** [Anders142536/FacAutoScreenshot#27]
I'm having an issue where everything after "Surfaces" is cut out because there are too many surfaces. I'm planning on getting rid of Factorissimo soon, but I can't see any other options, without hiding the entire section. Is there any way to fix this?
![image](https://user-images.githubusercontent.com/34276633/130896750-00dbe16e-3b7f-4994-9c8e-650503859d7f.png)
(The rest is out of the screen, I have it as high as possible)

**Comment by Anders142536** [comment]
Omg, how could I not think of this!

Sorry, but currently there is no way of fixing this. I will prioritize this, this should not be possible.

I will add a maximum height to the "surfaces box" and add a scrollbar to it if it exceeds that maximum height. I should have done that in the first place!

Sry for the late response, I somehow didn't get a notification at all from your issue.

**Comment by mechanikate** [comment]
Thank you, and it's fine about not seeing the notification! I didn't either for your message just now, strangely.

**Comment by Anders142536** [comment]
For some reason one is not automatically watching their own repositories. That's weird.

**Comment by Anders142536** [comment]
Issue fixed, there is now a scrollbar after 8 surfaces!

There are some imperfections. For example there is a 12px gap below the surface list items if there are less than 8 items there and i have no clue why this happens. but it works and solves your issue!
