### ISSUE TITLE
AutoScreenshot feature not using the selected resolution

### ISSUE THREAD

**Issue by RableJustRable** [Anders142536/FacAutoScreenshot#38]
**Game version:**
1.1.61
**Mod version:** 
2.4.5
**Log-file link:** 
https://pastebin.com/ckY9t8vg
**Save-file link:** 
N/A, happens on every save file including brand new ones
**A detailed description of what happened:**
The mod appears to be not using the resolution settings set by the player in the auto screenshots section of the gui and is instead selecting the resolution 1 lower than the player selected in the menu. I only encountered this bug in single player, did not test in multiplayer. This happens with both single tick screenshots and split screenshots.

15360x8640 (16K) produces 7680x4320 screenshots
7680x4320 (8K) produces 3840x2160 screenshots
3840x2160 (4K) produces 1920x1080 screenshots
1920x1080 (FullHD) produces 1280x720 screenshots
1280x720 (HD) produces 1280x720  screenshots

**Step-by-step instructions for reproduction:**
Start new game
Select nauvis under surfaces.
Set resolution to 16k
Set interval to 1 minute
Keep Single Tick Screenshots on.
Wait 1 minute and check output folder.

**Comment by Anders142536** [comment]
Thanks for the report!

Your description was very helpful, I fixed it.

Have fun using my mod :D

**Comment by RableJustRable** [comment]
Thanks for the quick fix! Can confirm it works correctly now :)
