### ISSUE TITLE
Crash on landing with Space ship in Space Exploration

### ISSUE THREAD

**Issue by Gammro** [Anders142536/FacAutoScreenshot#42]
**Game version: 1.1.76** 
**Mod version: 2.4.8** 
**Space Exploration: 0.6.101**
**Description:**

After travelling on a space ship and landing it at any location generates a crash. With the following excerpt from the log as message:

>  451.476 Script @__FacAutoScreenshot__/control.lua:508: INFO: surface spaceship-1 deleted
>  451.476 Error MainLoop.cpp:1288: Exception at tick 34321582: The mod Screenshot Toolkit (2.4.8) caused a non-recoverable error.
Please report this error to the mod author.
> Error while running event FacAutoScreenshot::on_pre_surface_deleted (ID 65)
\_\_FacAutoScreenshot\_\_/control.lua:513: attempt to index field '?' (a nil value)
stack traceback:
	\_\_FacAutoScreenshot__/control.lua:513: in function <\_\_FacAutoScreenshot\_\_/control.lua:507>

Attached is my [factorio-current.log](https://github.com/Anders142536/FacAutoScreenshot/files/10774642/factorio-current.log), with debug enabled

I've already removed the mod from the save and re-enabled it to test if that made it go away, with no result. Not sure what happens exactly as a friend of mine who runs almost the same mod set has no trouble at all with it.

**Steps to reproduce:**
- Enter a space ship
- Set destination
- Get a quick cup of coffee while the ship flies there
- Select a landing location and land
- Game crash

Thanks for the great mod, too bad I cant use it right now :(

**Comment by Anders142536** [comment]
Thanks for your report. I will treat this with high priority, but I currently have little time for modding stuff.

**Comment by Gammro** [comment]
I was trying your mod again, as I thought maybe a new factorio update might have fixed it, but it seems to also happen when I just delete a surface in Space Exploration.
![image](https://user-images.githubusercontent.com/14943181/229295870-fe5309d6-6eda-4fef-a7e6-b64a465a9a90.png)

**Comment by Gammro** [comment]
Sorry didnt mean to close it

**Comment by Gammro** [comment]
I found the cause of the error:

The toolkit makes a table entry for every player, and when a surface gets deleted it goes through every player in the save to clean up associated data for that surface, right? 

I've had another person join me waaaayyyy back once, before I've had it enabled. So they didn't have the associated data generated, which the script then tries to delete and causes a crash.

To fix this, add a check to see if the global.auto[player.index] exists before continuing, which makes the function ```on_pre_surface_deleted``` like this:
```
-- #region surfaces
local function on_pre_surface_deleted(event)
    log(l.info("surface " .. game.get_surface(event.surface_index).name .. " deleted"))

    -- delete entries of deleted surface
    for _, player in pairs(game.players) do
        if global.auto[player.index] ~= nil then --this is the new check
            local name = game.get_surface(event.surface_index).name
            if global.auto[player.index].doSurface[name] ~= nil then
                global.auto[player.index].doSurface[name] = nil
            end

            -- if the surface was in queue for a screenshot
            if global.queue[player.index] and global.queue[player.index][name] then
                queue.remove(player.index, name)
            end

            -- if there was an area selection on the surface
            if global.snip[player.index].surface_name == name then
                snip.resetArea(player.index)
            end
        end --this is the end of the new check
    end

    gui.initializeAllConnectedPlayers(queue.hasAnyEntries())
end
```

**Comment by Anders142536** [comment]
From a quick look this looks good to me. I'll merge it and release it during the weekend.

Thanks for your contribution!
